### ISSUE TITLE
[Bug] not using current namespace on macosx

### ISSUE THREAD

**Issue by fredleger** [guessi/kubectl-grep#13]
**Describe the bug**
Need to specify namespace to have results on macosx

**To Reproduce**
1. `kubectl grep pods nginx`
2. `kubectl grep pods nginx -n demo`

**Expected behavior**
I would have thought that it would use the current NS

**Screenshots**

**Environment (please complete the following information):**
 - Operation System: macOS
 - Kubernetes Version 1.12.9
Kubectl Version v1.14.3

**Additional context**
NA

**Comment by guessi** [comment]
@fredleger Thanks for report.

You're right, it should respect the value of the `namespace` value in `~/.kube/config`. I will mark this report as `enhancement`, and fix it later, but there's no ETA for the fix. If this feature matter to you, maybe you can try to create a pull-request for the fix :octocat:  _FYI, you may find the source code [HERE](https://github.com/guessi/kubectl-grep/blob/v1.1.0/pkg/utils/utils.go#L27-L34)._


Story behind, while I was designing this tool, my initial thought was that having namespace defined **explicitly** would be safer, especially for production environment. For now, please take this a hard limitation.
