### ISSUE TITLE
[Feature] Support CRDs

### ISSUE THREAD

**Issue by jasonstitt** [guessi/kubectl-grep#28]
**Is your feature request related to a problem? Please describe.**
Kubectl commands like `get` work with CRDs, i.e. I can do things like `kubectl get ingress`. But using `kubectl grep` I can only get the basic/default resource types.

**Describe the solution you'd like**
Support the CRDs installed on the cluster like `kubectl get` does, e.g. `kubectl grep ingress`, `kubectl grep mapping`, etc.

**Describe alternatives you've considered**
Only way is to go back to `kubectl get ... | grep ...`

**Comment by guessi** [comment]
@jasonstitt Sorry for the late reply.

Brief answer, there is no plan for supporting things like CRD in the near future.

Initially `kubectl-grep` is aim to solve the common pain point, find resource by keyword, but it didn't take CRD into consideration at the very beginning, all the resources are implemented [separately](https://github.com/guessi/kubectl-grep/tree/master/pkg/resources). I'm afraid there's no simple way to support CRD right now.

Maybe you could try another awesome project,
- https://github.com/corneliusweig/ketall

Or find one suitable kubectl-plugins that could meet your requirements,
- https://github.com/topics/kubectl-plugins
